export const ErrorCodeMap: Record<number, string> = {
    999: "Lỗi máy chủ nội bộ",
    1000: "Khoá không hợp lệ",
    1001: "Người dùng đã tồn tại",
    1002: "Email đã tồn tại",
    1003: "Không tìm thấy người dùng",
    1004: "Mã OTP không hợp lệ",
    1005: "Mã OTP đã hết hạn",
    1006: "Tên đăng nhập không hợp lệ",
    1007: "Mật khẩu không hợp lệ",
    1008: "Người dùng không tồn tại",
    1009: "Chưa xác thực",
    1010: "Bạn không có quyền thực hiện hành động này",
    1011: "Tuổi của bạn không hợp lệ",
    1012: "Không tìm thấy mã OTP / Vui lòng đợi 30 giây để gửi lại",
    1013: "OTP chưa được xác thực",
    1014: "Không tìm thấy thể loại",
    1015: "Thể loại đã tồn tại",
    1016: "Không tìm thấy phim",
    1017: "Phim đã tồn tại",
    1018: "Không tìm thấy người (Đạo diễn/Diễn viên)",
    1019: "Người (Đạo diễn/Diễn viên) đã tồn tại",
    1020: "Không tìm thấy banner",
    1021: "Banner đã tồn tại",
    1022: "Không tìm thấy sự kiện",
    1023: "Sự kiện đã tồn tại",
    1024: "Vui lòng cung cấp ID phim",
    1025: "Không được phép sử dụng ID sự kiện",
    1026: "Vui lòng cung cấp ID sự kiện",
    1027: "Không được phép sử dụng ID phim",
    1028: "Loại banner không hợp lệ",
    1029: "Rạp chiếu đã tồn tại",
    1030: "Không tìm thấy rạp chiếu",
    1031: "Phòng chiếu đã tồn tại",
    1032: "Không tìm thấy phòng chiếu",
    1033: "Ghế đã tồn tại",
    1034: "Không tìm thấy ghế",
    1035: "Suất chiếu đã tồn tại",
    1036: "Không tìm thấy suất chiếu",
    1037: "Ghế của suất chiếu đã tồn tại",
    1038: "Không tìm thấy ghế của suất chiếu",
    1039: "Giá suất chiếu đã tồn tại",
    1040: "Không tìm thấy giá suất chiếu",
    1041: "Đồ ăn/thức uống đã tồn tại",
    1042: "Không tìm thấy đồ ăn/thức uống",
    1043: "Khuyến mãi đã tồn tại",
    1044: "Không tìm thấy khuyến mãi",
    1045: "Khuyến mãi đã hết hạn",
    1046: "Khuyến mãi đã hết lượt sử dụng",
    1047: "Không đủ điều kiện áp dụng khuyến mãi",
    1048: "Đơn hàng đã tồn tại",
    1049: "Không tìm thấy đơn hàng",
    1050: "Ghế được chọn không hợp lệ",
    1051: "Đồ ăn được chọn không hợp lệ",
    1052: "Ghế đã được đặt trước đó",
    1053: "Dữ liệu ghế không hợp lệ",
    1054: "Không tìm thấy giá",
    1055: "Không tìm thấy hạng thành viên",
    1056: "Suất chiếu đã bị huỷ trước đó",
    1057: "Chỉ có thể cập nhật suất chiếu khi đang ở trạng thái Lên lịch (SCHEDULED)",
    1058: "Suất chiếu đã có ghế được đặt hoặc đã bán, không thể cập nhật",
    1059: "Kích thước dữ liệu đầu vào không khớp",
    1060: "Không tìm thấy loại ghế",
    1061: "Tạo mã QR thất bại",
    1062: "Ngày phát hành phim không hợp lệ",
    1063: "Phòng chiếu đang có suất chiếu hoạt động, không thể đổi loại phòng",
    1064: "Phòng chiếu đã được thiết lập ghế",
    1065: "Phim đã ngừng chiếu, không thể tạo suất chiếu mới",
    1066: "Thời gian bắt đầu hoặc kết thúc bị trùng lặp với một suất chiếu khác",
    1067: "Suất chiếu phải cách các suất chiếu khác ít nhất 15 phút",
    1068: "Đồ ăn không thuộc rạp chiếu đã chọn",
    1069: "Đồ ăn đã hết hàng",
    1073: "Bạn đã nhận voucher này rồi",
    1074: "Voucher không khả dụng",
    1070: "Đơn hàng đã được sử dụng",
    1071: "Mã QR không hợp lệ",
    1072: "Trạng thái đơn hàng không cho phép check-in",
    1075: "Voucher này đã được sử dụng",
    1076: "Không tìm thấy voucher trong tài khoản của bạn",
    1077: "Trạng thái khuyến mãi không hợp lệ",
    1078: "Hạng thành viên đã tồn tại",
    1079: "Không tìm thấy đánh giá",
    1080: "Bạn đã đánh giá phim này rồi",
    1081: "Bạn chỉ có thể đánh giá sau khi đã xem phim",
    1082: "Bạn không sở hữu đánh giá này",
    1083: "Refresh token không hợp lệ hoặc đã hết hạn",
    1084: "Không thể tạo suất chiếu trong quá khứ",
    1085: "Phim đã được tạm dừng",
    1086: "Phim chưa được tạm dừng, không thể chiếu lại",
    1087: "Ghế đã được đặt bởi người khác",
    1088: "Đơn hàng không ở trạng thái chờ xử lý",
};

export const getErrorMessage = (code?: number, defaultMessage?: string) => {
    if (code && ErrorCodeMap[code]) {
        return ErrorCodeMap[code];
    }
    return defaultMessage || "Đã xảy ra lỗi không xác định";
};
